defaults:
  - agents: oc_ddpm_agent

agent_name: oc_ddpm
log_dir: logs/real_robot_${task_suite}/

train_data_path: /media/alr_admin/Data/atalay/data  # just for dataset init

task_suite: pickPlacing  # pickPlacing cupStacking insertion
if_sim: False

# insert wandb here
wandb:
  entity: atalaydonat
  project: d3il

group: ${task_suite}_${agent_name}

hydra:
  run:
    dir: ${log_dir}/runs/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/sweeps/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

seed: 42

# Network
hidden_dim: 128
num_hidden_layers: 6

# transformer
n_layer: 4
n_head: 4
n_embd: 72

# Training
train_batch_size: 64
val_batch_size: 256
num_workers: 4
device: 'cuda'
epoch: 100
eval_every_n_epochs: 10
scale_data: True

# Environment
obs_dim: 10 # not used
action_dim: 8
max_len_data: 600
window_size: 5

action_seq_size: 5
obs_seq_len: 1

# Dataset
trainset:
  _target_: environments.dataset.real_robot_dataset.Real_Robot_Dataset
  data_directory: ${train_data_path}
  task_suite: ${task_suite}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  if_sim: ${if_sim}

valset:
  _target_: environments.dataset.real_robot_dataset.Real_Robot_Dataset
  data_directory: ${train_data_path}
  task_suite: ${task_suite}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  if_sim: ${if_sim}


# Simulation
simulation:
  _target_: simulation.real_robot.RealRobot
  device: ${device}